route:
  group_by: ['alertname','team']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: slack-default
  routes:
    - matchers: ['severity="critical"']
      receiver: slack-page
      repeat_interval: 2h
    - matchers: ['severity="page"']
      receiver: slack-page
      repeat_interval: 2h
    - matchers: ['severity="ticket"']
      receiver: slack-ticket
    - matchers: ['severity="warning"']
      receiver: slack-warning

receivers:
  - name: slack-default
    slack_configs: [{send_resolved: true, channel: '#ops'}]
  - name: slack-page
    slack_configs: [{send_resolved: true, channel: '#oncall'}]
  - name: slack-ticket
    slack_configs: [{send_resolved: true, channel: '#quality'}]
  - name: slack-warning
    slack_configs: [{send_resolved: true, channel: '#quality'}]
