route:
  receiver: default
  routes:
  - matchers: ['team="search"', 'severity="warning"']
    receiver: search-slack
receivers:
- name: default
  webhook_configs:
  - url: 'http://localhost:9093/webhook'
- name: search-slack
  slack_configs:
  - channel: '#search-alerts'
    webhook_url: '${SLACK_WEBHOOK_URL}'
