repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Shadow 경로 커밋 금지
  - repo: local
    hooks:
      - id: deny-shadow-paths
        name: Deny shadow tracked paths
        entry: bash -c 'git diff --cached --name-only | grep -E "^duri_(core|brain|evolution|control)(/|$)" && echo "❌ Do not commit shadow paths (duri_core, duri_brain, duri_evolution, duri_control)" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: deny-shadow-submodules
        name: Deny shadow submodules in .gitmodules
        entry: bash -c 'git diff --cached .gitmodules 2>/dev/null | grep -E "^\+(url|path).*=.*duri_(core|brain|evolution|control)[^_]" && echo "❌ Do not add shadow submodules to .gitmodules (use *_legacy only)" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: deny-shadow-symlink-change
        name: Deny modifying top-level shadow symlinks
        entry: bash -c 'git diff --name-status --cached | grep -E "^(A|M|R).*(^|/)(duri_core|duri_brain|duri_evolution|duri_control)$" && { echo "❌ Do not modify shadow symlinks directly."; exit 1; } || true'
        language: system
        pass_filenames: false
      - id: deny-prod-compose-change
        name: Deny editing prod compose without approval
        entry: bash -c '[ -z "$(git diff --name-only --cached | grep -E "^docker-compose\.yml$")" ] || { echo "⚠️ Editing docker-compose.yml requires careful review."; exit 0; }'
        language: system
        pass_filenames: false
