repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Shadow 경로 커밋 금지
  - repo: local
    hooks:
      - id: deny-shadow-paths
        name: Deny shadow tracked paths
        entry: bash -c 'git diff --cached --name-only | grep -E "^duri_(core|brain|evolution|control)(/|$)" && echo "❌ Do not commit shadow paths (duri_core, duri_brain, duri_evolution, duri_control)" && exit 1 || exit 0'
        language: system
        pass_filenames: false
