version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=8GB
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - ./data/prometheus:/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9090/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - duri_core
      - duri_brain
      - duri_evolution
      - duri_control
      - duri-postgres
      - duri-redis
    profiles: ["monitoring"]

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_SECURITY_COOKIE_SECURE: "false"
      GF_SECURITY_ALLOW_EMBEDDING: "false"
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_ROOT_URL: http://localhost:3000/
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    profiles: ["monitoring"]

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.27.0
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --log.level=info
      - --cluster.listen-address=
    volumes:
      - ./ops/observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./ops/observability/slack_webhook_url:/etc/alertmanager/secrets/slack_webhook_url:ro
    profiles: ["monitoring"]

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    profiles: ["monitoring"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8084:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    profiles: ["monitoring"]

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: redis://duri-redis:6379
    ports:
      - "9121:9121"
    profiles: ["monitoring"]

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: postgres://postgres:${POSTGRES_PASSWORD:-duriCHANGE_ME_DB_PASSWORD}@duri-postgres:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"
    profiles: ["monitoring"]

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.24.0
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    profiles: ["monitoring"]

volumes:
  grafana_data:
