services:
  duri_control_container:
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8083/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

  duri_core_container:
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8080)); s.close(); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  duri_evolution_container:
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8082)); s.close(); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  duri_brain_container:
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8081)); s.close(); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  duri-postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  duri-redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
