[tool.mutmut]
paths_to_mutate = ["duri_core", "duri_brain", "duri_evolution"]
tests_dir = "tests"
runner = "python -m pytest tests/test_imports.py -q"
backup = false
dict_synonyms = "dict,mapping"

[tool.radon]
cc_threshold = "C"  # B 이상이면 경고, C부터 실패
mi_min = 65         # 유지보수성 지수 최소
show_complexity = true
show_closures = true

[tool.xenon]
max-absolute = "B"
max-modules = "B"
max-average = "B"
exclude = ["tests/", "var/", ".duri/", "DuRiCore/backup_repository/"]
