                                                                                                                                                                                                                           definition                                                                                                                                                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  SELECT feedback_events.id,                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     feedback_events.ts,                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     feedback_events.track,                                                                                                                                                                                                                                                                                                                                                                                                                                     +
     feedback_events.ok,                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     feedback_events.hallucination,                                                                                                                                                                                                                                                                                                                                                                                                                             +
     feedback_events.latency_s,                                                                                                                                                                                                                                                                                                                                                                                                                                 +
     feedback_events.cost_usd,                                                                                                                                                                                                                                                                                                                                                                                                                                  +
     feedback_events.meta,                                                                                                                                                                                                                                                                                                                                                                                                                                      +
     feedback_events.meta_user_id,                                                                                                                                                                                                                                                                                                                                                                                                                              +
     feedback_events.meta_model_id                                                                                                                                                                                                                                                                                                                                                                                                                              +
    FROM feedback_events                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   WHERE ((feedback_events.meta_user_id IS NOT NULL) AND (feedback_events.meta_user_id !~ '^(shadow_test|cand_fill|prod_fill|prod_fix|final_test|smoke_test|legacy_.*)$'::text) AND (COALESCE((feedback_events.meta ->> 'tag'::text), ''::text) <> 'historical_noise'::text) AND (COALESCE(((feedback_events.meta ->> 'is_gold'::text))::boolean, false) = false) AND ((COALESCE(feedback_events.source, ''::character varying))::text <> 'gold@inject'::text));
(1 row)

