global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs: [{ targets: ['node_exporter:9100'] }]
  - job_name: 'redis_exporter'
    static_configs: [{ targets: ['redis_exporter:9121'] }]
  - job_name: 'postgres_exporter'
    static_configs: [{ targets: ['postgres_exporter:9187'] }]
  - job_name: 'blackbox_exporter'
    static_configs: [{ targets: ['blackbox_exporter:9115'] }]
  - job_name: 'alertmanager'
    static_configs: [{ targets: ['alertmanager:9093'] }]
  - job_name: 'prometheus'
    static_configs: [{ targets: ['prometheus:9090'] }]
