groups:
- name: quality-alerts
  interval: 1m
  rules:
  # A의 즉시 급락
  - alert: QualityDropImmediate
    expr: duri_ndcg_at_k{k="3",scope="all",domain="ALL"} < 0.80
    for: 5m
    labels: {severity: critical, team: search}
    annotations:
      summary: "nDCG 급락 (즉시)"
      description: "k=3, domain=ALL"

  # A의 WoW 회귀
  - alert: QualityWoWRegression
    expr: duri_ndcg_wow_pct < -0.05
    for: 30m
    labels: {severity: warning, team: search}
    annotations:
      summary: "nDCG WoW 하락 >5%"
      description: "주간 대비 하락"

  # A의 z-score 이상
  - alert: QualityZScoreAnomaly
    expr: duri_ndcg_z <= -2 or duri_mrr_z <= -2
    for: 15m
    labels: {severity: warning, team: search}
    annotations:
      summary: "품질 이상 징후(z<=-2)"
      description: "MA7/STD7 기준 z-score 이상"

  # B의 SLO breach
  - alert: RerankerNDCGSLOBreached
    expr: duri_ndcg_errbudget > 0
    for: 30m
    labels: {severity: page, team: search}
    annotations:
      summary: "nDCG@3 SLO breach"
      description: "MA7 nDCG@3 < 0.90 (err={{ $value }})"

  - alert: RerankerMRRSLOBreached
    expr: duri_mrr_errbudget > 0
    for: 30m
    labels: {severity: page, team: search}
    annotations:
      summary: "MRR SLO breach"
      description: "MA7 MRR < 0.88 (err={{ $value }})"

  - alert: RerankerQualityDoDDrop
    expr: (duri_ndcg_at_k{k="3",scope="all",domain="ALL"} - duri_ndcg_at_k{k="3",scope="all",domain="ALL"} offset 1d) < -0.03
    for: 15m
    labels: {severity: ticket, team: search}
    annotations:
      summary: "Quality sudden drop (DoD >3%)"
      description: "전일 대비 3% 이하락"

  # MRR SLO breach alert
  - alert: MRR_SLO_Breach
    expr: duri_mrr_ma7 < 0.88
    for: 15m
    labels: {severity: warning, team: search}
    annotations:
      description: "MRR@3 MA7={{ $value | printf \"%.3f\" }}"

  # Day-over-Day drop alert
  - alert: Quality_DayOverDay_Drop
    expr: (duri_ndcg_at_k{k="3",scope="all",domain="ALL"} - duri_ndcg_at_k{k="3",scope="all",domain="ALL"} offset 1d) < -0.03
    for: 10m
    labels: {severity: warning, team: search}
    annotations:
      summary: "nDCG day-over-day drop >3%"
      description: "Δ1d={{ $value | printf \"%.3f\" }}"
