groups:
- name: quality-slo
  interval: 1m
  rules:
  - record: duri_ndcg_ma7
    expr: avg_over_time(duri_ndcg_at_k{k="3",scope="all",domain="ALL"}[7d])
  - record: duri_mrr_ma7
    expr: avg_over_time(duri_mrr_at_k{k="3",scope="all",domain="ALL"}[7d])
  - record: duri_recall3_ma7
    expr: avg_over_time(duri_recall_at_k{k="3",scope="all",domain="ALL"}[7d])

  - record: duri_ndcg_errbudget
    expr: (0.90 - duri_ndcg_ma7)
  - record: duri_mrr_errbudget
    expr: (0.88 - duri_mrr_ma7)
  - record: duri_recall3_errbudget
    expr: (0.98 - duri_recall3_ma7)
