groups:
- name: quality-alerts
  interval: 1m
  rules:
  # A의 즉시 급락
  - alert: QualityDropImmediate
    expr: duri_ndcg_at_k{k="3",scope="all",domain="ALL"} < 0.80
    for: 5m
    labels:
      severity: critical
      team: search
      runbook_url: "https://docs.example.com/runbooks/quality-alerts"
    annotations:
      summary: "nDCG 급락 (즉시)"
      description: "k=3, domain=ALL"

  # B의 WoW 하락
  - alert: QualityWoWDrop
    expr: duri_ndcg_wow_pct < -0.05
    for: 10m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/quality-alerts"
    annotations:
      summary: "nDCG WoW 하락 >5%"
      description: "주간 대비 하락"

  # C의 이상 징후
  - alert: QualityAnomaly
    expr: duri_ndcg_z <= -2 or duri_mrr_z <= -2
    for: 15m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/quality-alerts"
    annotations:
      summary: "품질 이상 징후(z<=-2)"
      description: "MA7/STD7 기준 z-score 이상"

  # D의 DoD 하락
  - alert: QualityDayOverDayDrop
    expr: (duri_ndcg_at_k{k="3",scope="all",domain="ALL"} - duri_ndcg_at_k{k="3",scope="all",domain="ALL"} offset 1d) < -0.03
    for: 10m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/quality-alerts"
    annotations:
      summary: "nDCG day-over-day drop >3%"
      description: "Δ1d={{ $value | printf \"%.3f\" }}"

  # MRR SLO breach alert
  - alert: MRR_SLO_Breach
    expr: duri_mrr_ma7 < slo_mrr_target
    for: 15m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/mrr-slo"
    annotations:
      summary: 'MRR MA7 below SLO target'
      description: "MRR@3 MA7={{ $value | printf \"%.3f\" }}"

  # MRR 빠른 감지 보조 경보 (15분 지속)
  - alert: MRR_Quick_Drop
    expr: avg_over_time(duri_mrr_at_k{k="3",scope="all",domain="ALL"}[15m]) < 0.85
    for: 15m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/mrr-quick-drop"
    annotations:
      summary: "MRR 빠른 감지 (<0.85)"
      description: "MRR@3: {{ $value | printf \"%.3f\" }}"

  # Quality Day-over-Day Drop (DoD)
  - alert: Quality_DayOverDay_Drop
    expr: (duri_ndcg_at_k{k="3",scope="all",domain="ALL"} - duri_ndcg_at_k{k="3",scope="all",domain="ALL"} offset 1d) < -0.03
    for: 10m
    labels:
      severity: warning
      team: search
      runbook_url: "https://docs.example.com/runbooks/quality-dod"
    annotations:
      summary: "nDCG day-over-day drop >3%"
      description: "Δ1d={{ $value | printf \"%.3f\" }}"
