groups:
- name: quality-burn
  interval: 1m
  rules:
  # "나쁜 상태"를 0/1로 바이너리화
  - record: duri_ndcg3_bad
    expr: duri_ndcg_errbudget > 0
  - record: duri_mrr3_bad
    expr: duri_mrr_errbudget > 0

  # 이중 윈도우 버닝(빠른/느린)
  - record: duri_ndcg3_bad_rate_2h
    expr: avg_over_time(duri_ndcg3_bad[2h])
  - record: duri_ndcg3_bad_rate_24h
    expr: avg_over_time(duri_ndcg3_bad[24h])
  - record: duri_mrr3_bad_rate_2h
    expr: avg_over_time(duri_mrr3_bad[2h])
  - record: duri_mrr3_bad_rate_24h
    expr: avg_over_time(duri_mrr3_bad[24h])
