FROM duri-base:latest

WORKDIR /app
ENV PYTHONPATH=/app

# Core 서비스 파일 복사
COPY duri_core/ /app/duri_core/

# Core 서비스 의존성 설치
COPY duri_core/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Core 서비스 실행
CMD ["python", "duri_core/run.py"]
