# Prometheus 알람 룰 최종본 - 레코딩 룰 기반

groups:
  - name: duri-integrity
    rules:
      - alert: DuRiIntegrityTampered
        expr: increase(duri:integrity:status:tampered[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: duri-integrity
        annotations:
          summary: 'Integrity tampered detected'
          description: 'HMAC or manifest tamper detected in last 5m.'
          runbook_url: 'https://your.runbook/url#tampered'

      - alert: DuRiIntegrityCorrupted
        expr: increase(duri:integrity:status:corrupted[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: duri-integrity
        annotations:
          summary: 'Integrity corrupted'
          description: 'Modified/missing files were detected.'
          runbook_url: 'https://your.runbook/url#corrupted'

      - alert: DuRiIntegrityPolicyChanged
        expr: increase(duri:integrity:status:policy_changed[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: duri-integrity
        annotations:
          summary: 'Integrity policy changed'
          description: 'Ignore or schema policy changed. Review and approve.'
          runbook_url: 'https://your.runbook/url#policy_changed'

      - alert: DuRiIntegrityScanSlow
        expr: avg_over_time(duri:integrity:scan:duration_ms[15m]) > 2000
        for: 10m
        labels:
          severity: warning
          service: duri-integrity
        annotations:
          summary: 'Integrity scan slow'
          description: 'Average scan duration > 2s for 10m.'
          runbook_url: 'https://your.runbook/url#scan_slow'

      - alert: DuRiIntegrityHmacFailure
        expr: increase(duri:integrity:hmac:status{checksums_ok="false"}[5m]) > 0 or increase(duri:integrity:hmac:status{metadata_ok="false"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: duri-integrity
        annotations:
          summary: 'HMAC signature verification failed'
          description: 'Checksums or metadata HMAC signature verification failed.'
          runbook_url: 'https://your.runbook/url#hmac_failure'

      - alert: DuRiIntegrityFilesSpike
        expr: (duri:integrity:files:missing / duri:integrity:files:total) > 0.3
        for: 0m
        labels:
          severity: warning
          service: duri-integrity
        annotations:
          summary: 'Integrity files spike detected'
          description: 'Missing files exceed 30% of total files.'
          runbook_url: 'https://your.runbook/url#files_spike'

      - alert: DuRiIntegrityHmacDisabled
        expr: duri:integrity:hmac:status{enabled="false"} == 1
        for: 5m
        labels:
          severity: warning
          service: duri-integrity
        annotations:
          summary: 'HMAC signature disabled'
          description: 'HMAC signature verification is disabled.'
          runbook_url: 'https://your.runbook/url#hmac_disabled'

      - alert: DuRiIntegrityFailureRateHigh
        expr: duri:integrity:failure_rate > 0.1
        for: 5m
        labels:
          severity: warning
          service: duri-integrity
        annotations:
          summary: 'Integrity failure rate high'
          description: 'Integrity failure rate > 0.1 events/s for 5m.'
          runbook_url: 'https://your.runbook/url#failure_rate_high'
