global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus_recording_rules.yml"
  - "prometheus_rules_final.yml"
  - "prometheus_slo_recording_rules.yml"

scrape_configs:
  - job_name: 'duri-services'
    static_configs:
      - targets: ['duri_core:8080', 'duri_brain:8081', 'duri_evolution:8082', 'duri_control:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
