---
name: quality
on: [pull_request]
env:
  AM_VER: "0.28.0"
  AM_IMG: "prom/alertmanager@sha256:abc123def456"
  PROM_VER: "2.55.0"
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install promtool & jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          curl -fsSL -o prom.tgz https://github.com/prometheus/prometheus/releases/download/v${PROM_VER}/prometheus-${PROM_VER}.linux-amd64.tar.gz
          tar -xzf prom.tgz
          sudo mv prometheus-${PROM_VER}.linux-amd64/promtool /usr/local/bin/promtool
          promtool --version; docker run --rm prom/alertmanager:${AM_VER} --version
      - name: Alertmanager config check (rendered)
        if: ${{ github.event.pull_request.head.repo.fork == false }}
        run: |
          export SLACK_WEBHOOK_URL='${{ secrets.SLACK_WEBHOOK_URL }}'
          docker run --rm -e SLACK_WEBHOOK_URL \
            -v "$PWD/alertmanager:/etc/alertmanager" \
            --entrypoint sh prom/alertmanager:${AM_VER} -lc '
              apk add --no-cache gettext >/dev/null 2>&1 || true
              envsubst < /etc/alertmanager/alertmanager.yml > /tmp/am.yml &&
              /bin/amtool check-config /tmp/am.yml
            '
      - name: Alertmanager config check (fork-safe)
        if: ${{ github.event.pull_request.head.repo.fork == true }}
        run: |
          export SLACK_WEBHOOK_URL='https://example.invalid'
          docker run --rm -e SLACK_WEBHOOK_URL \
            -v "$PWD/alertmanager:/etc/alertmanager" \
            --entrypoint sh prom/alertmanager:${AM_VER} -lc '
              apk add --no-cache gettext >/dev/null 2>&1 || true
              envsubst < /etc/alertmanager/alertmanager.yml > /tmp/am.yml &&
              /bin/amtool check-config /tmp/am.yml
            '
      - run: make prom-rules-ci
      - run: make prom-dup-guard
      - run: make alert-labels-guard
      - run: make prom-rules-test
