# configs/backup_topology.yml
# 백업 목적지 우선순위 정의 (Single Source of Truth)
version: 1

backup_destinations:
  primary: /mnt/hdd/ARCHIVE/FULL
  secondary: /mnt/usb/두리백업
  tertiary: /mnt/c/Users/admin/Desktop/두리백업
  cold_home: /mnt/f/DuRiSafe_HOME/FULL
  cold_hosp: /mnt/e/DuRiSafe_HOSP/FULL

# 선택 기준
selection_criteria:
  - writable: 쓰기 가능 여부
  - priority: 우선순위 순서
  - available: 마운트/접근 가능 여부

# 검증 기준
validation:
  - latest_full_exists: 최신 FULL 백업 존재
  - integrity_check: 무결성 검증 통과
  - size_threshold: 최소 크기 기준

# 로깅
logging:
  stamp_file: .last_full_backup.txt
  topology_file: .topology.json
  reason_logging: true
