coding:
  canary: 0.0
coding_canary:
  error_rate_threshold: 0.05
  latency_threshold_ms: 2000
  monitoring_window_hours: 12
  percentage: 5.0
  quality_threshold: 85.0
  rollout_strategy: gradual
  success_rate_threshold: 0.95
global_canary:
  alert_channels:
  - slack
  - email
  auto_rollback_enabled: true
  escalation_threshold_minutes: 30
  max_rollout_percentage: 50.0
  min_monitoring_hours: 12
medical:
  canary: 0.05
medical_canary:
  error_rate_threshold: 0.05
  latency_threshold_ms: 800
  monitoring_window_hours: 24
  percentage: 10.0
  quality_threshold: 85.0
  rollout_strategy: gradual
  success_rate_threshold: 0.95
rehab:
  canary: 0.0
rehab_canary:
  error_rate_threshold: 0.1
  latency_threshold_ms: 1000
  monitoring_window_hours: 48
  percentage: 5.0
  quality_threshold: 80.0
  rollout_strategy: gradual
  success_rate_threshold: 0.9
