day: 36
variants: [A, B]
paths:
  inputs: artifacts/day36
  outputs: outputs/day36
metrics:
  primary: "objective_delta"
  additional: ["t_stat", "p_value"]
stat_test: "welch_t"
promotion:
  rule: "objective_delta > 0 and p_value <= 0.05"
seed: 42