day: 38
variants: [A, B]
paths:
  inputs: artifacts/day38
  outputs: outputs/day38
metrics:
  primary: "objective_delta"
  additional: ["t_stat", "p_value"]
stat_test: "welch_t"
promotion:
  enabled: true
  policy: "policies/promotion.yaml"
seed: 42
