name: proof-gates
on: [pull_request]
jobs:
  gates:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: G1 - Booting Smoke Test
        run: bash tools/smoke.sh 150
      - name: G2 - Log ABI Check
        run: bash tools/log_abi_check.sh
      - name: G3 - Metrics ABI Guard
        run: bash tools/metrics_guard.sh
      - name: G4 - Settings Priority Gate
        run: bash tools/settings_gate.sh
  day38-m3-suggest:
    if: contains(github.event.pull_request.labels.*.name, 'auto-fix:suggest')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt || true
      - name: Run suggester on last failed log (demo)
        run: |
          echo "E   ModuleNotFoundError: No module named 'foo_bar'" | python3 tools/auto_fix_suggester.py > suggest.json
          cat suggest.json
      - name: Comment suggestions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          body=$(jq -r '. | @json' suggest.json)
          gh pr comment ${{ github.event.pull_request.number }} --body "🛠️ **Auto Fix Suggestions (M3 demo)**\n\n\`\`\`json\n$(cat suggest.json)\n\`\`\`"
