schema: pou.canary.metrics.v1
domain: medical
latency:
  p95_ms: 800
  p99_ms: 1500
quality:
  hitl_min_score: 85
safety:
  high_risk_miss_pct_max: 0.1
  banned_phrase_incidents: 0
explainability:
  trace_coverage_pct_min: 95
error:
  error_rate_pct_max: 0.5
