day: 39
variants: [A, B]
paths:
  inputs: artifacts/day39
  outputs: outputs/day39
metrics:
  primary: "objective_delta"
  additional: ["t_stat", "p_value"]
stat_test: "welch_t"
promotion:
  enabled: true
  rule: "policy"
  policy: "policies/promotion.yaml"
seed: 42
