# 15분 bin, 도메인별 수집·집계·알람
bin_minutes: 15
domains: [medical, rehab, coding]
log_globs:
  medical: "samples/logs/medical_*.jsonl"
  rehab:   "samples/logs/rehab_*.jsonl"
  coding:  "samples/logs/coding_*.jsonl"

# 목적함수 평가 설정( Day35 그대로 사용 )
objective:
  config: "configs/objective_params.yaml"
  weight_preset: "safety_first"
  evaluator: "tools/evaluate_objective.py"

# 알람 임계 (운영 가드)
alerts:
  fail_rate_p95_threshold: 0.008     # 0.8%
  fail_rate_persist_bins: 2          # 2 bins = 30분 지속 시 경보
  latency_p95_ms_threshold: 1800
  latency_persist_bins: 2

# 산출물 경로
outdir:
  bins:   "artifacts/day38/bins"        # 15분 집계 JSON
  series: "artifacts/day38/series"      # 도메인별 시계열 CSV
  alerts: "artifacts/day38/alerts"      # 경보 이벤트 로그
  daily:  "artifacts/day38/daily"       # 일일 리포트/민감도
