grid:
  sampling_rate: [0.25, 0.5, 0.75, 1.0]
  serialization: ["json", "msgpack", "protobuf"]
  compression: ["none", "gzip", "zstd"]
runner:
  cmd: "bash tools/run_trace_bench.sh --sampling {sampling_rate} --ser {serialization} --comp {compression} --out {out_json}"
io:
  slo_metrics_json: "slo_sla_dashboard_v1/metrics.json"
  out_dir: "trace_v2_perf_tuned/sweeps"
