#!/usr/bin/env python3
# Auto-PR Generator: Create PR with patch candidates and metric comparisons
# Purpose: L3 pipeline - automated PR creation with EV/h impact estimates
# Enhanced: Auto-merge support, labels, merge queue integration
# Usage: python3 scripts/ops/evolution/auto_pr.py <validation_result.json>

import json
import sys
import subprocess
import os
from datetime import datetime
from pathlib import Path

def get_git_repo():
    """Get git repository root"""
    result = subprocess.run(
        ['git', 'rev-parse', '--show-toplevel'],
        capture_output=True,
        text=True
    )
    return result.stdout.strip()

def get_current_branch():
    """Get current git branch"""
    result = subprocess.run(
        ['git', 'branch', '--show-current'],
        capture_output=True,
        text=True
    )
    return result.stdout.strip()

def estimate_ev_delta(validation_data):
    """Estimate EV/h delta based on metric improvements"""
    # Gradient weights (from user's specification)
    weights = {
        'ks_p': 0.35,
        'unique_ratio': 0.30,
        'sigma': 0.20,
        'n': 0.10,
        'slo_green': 0.05
    }
    
    delta = (
        validation_data.get('improvement_estimate', {}).get('delta_ks_p', 0) * weights['ks_p'] +
        validation_data.get('improvement_estimate', {}).get('delta_unique', 0) * weights['unique_ratio'] +
        validation_data.get('improvement_estimate', {}).get('delta_sigma', 0) * weights['sigma']
    )
    
    return delta

def create_pr_body(validation_file, patch_file):
    """Create PR body with metrics and impact"""
    with open(validation_file) as f:
        validation = json.load(f)
    
    with open(patch_file) as f:
        patch = json.load(f)
    
    delta_ev = estimate_ev_delta(validation)
    
    body = f"""## Auto-Generated PR: Evolution Pipeline

### Current Metrics
- KS_p: {patch['current_metrics']['ks_p']:.3f}
- unique_ratio: {patch['current_metrics']['unique_ratio']:.3f}
- sigma: {patch['current_metrics']['sigma']:.3f}

### Estimated Improvements
- ΔKS_p: {validation['improvement_estimate']['delta_ks_p']:.3f}
- Δunique_ratio: {validation['improvement_estimate']['delta_unique']:.3f}
- Δsigma: {validation['improvement_estimate']['delta_sigma']:.3f}

### EV/h Impact
**Estimated ΔEV/h: {delta_ev:.3f}**

### Risk Assessment
- P(break): {validation['risk_estimate']['p_break']:.3f}
- Odds Ratio: {validation['improvement_estimate']['odds_ratio']:.2f}
- Validation: {'✅ PASSED' if validation['validation']['passed'] else '❌ FAILED'}

### Weak Points Addressed
{chr(10).join(f'- {wp}' for wp in patch['weak_points'])}

### Patch Candidates
{len(patch.get('candidates', []))} candidates generated

### Labels
- `auto`
- `canary-ready`
- `dr-safe`

---
*Generated by DuRi L3 Evolution Pipeline at {datetime.now().isoformat()}*
"""
    return body

def main():
    if len(sys.argv) < 2:
        print("Usage: auto_pr.py <validation_result.json>", file=sys.stderr)
        sys.exit(1)
    
    validation_file = sys.argv[1]
    patch_file = validation_file.replace('.validation.json', '.json')
    
    if not Path(validation_file).exists():
        print(f"Validation file not found: {validation_file}", file=sys.stderr)
        sys.exit(1)
    
    repo_root = get_git_repo()
    os.chdir(repo_root)
    
    # Create branch
    branch_name = f"auto/evolution-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    subprocess.run(['git', 'checkout', '-b', branch_name], check=True)
    
    # Create PR body
    pr_body = create_pr_body(validation_file, patch_file)
    
    # Write PR body to file
    pr_body_file = f".reports/evolution/pr_body_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    Path(pr_body_file).parent.mkdir(parents=True, exist_ok=True)
    with open(pr_body_file, 'w') as f:
        f.write(pr_body)
    
    print(f"[PR_BODY] Written to {pr_body_file}")
    print("\n" + pr_body)
    
    # Note: Actual PR creation would use GitHub CLI or API
    # gh pr create --title "Auto: Evolution Pipeline Patch" --body-file "$pr_body_file" \
    #   --label "auto,canary-ready,dr-safe" \
    #   --base main
    
    # Auto-merge enable (if checks pass)
    # gh pr merge --auto --squash "$branch_name"

if __name__ == '__main__':
    main()

