name: AgentOps Nightly Eval
on:
  schedule:
    - cron: "15 18 * * *"   # 매일 03:15 KST
  workflow_dispatch: {}
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: pip install flask
      - name: Run eval suite
        run: bash scripts/run_agent_evals.sh
      - name: Sanity & budget guard
        run: |
          test -s eval_report.json
          jq -e '.success_rate >= 0.85 and .hallucination_rate <= 0.03' eval_report.json
      - name: Upload eval report
        uses: actions/upload-artifact@v4
        with:
          name: eval_report
          path: eval_report.json
