name: automerge-ops
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
permissions: { contents: write, pull-requests: write, checks: read }
jobs:
  merge:
    if: >
      startsWith(github.event.pull_request.head.ref, 'ops/') &&
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      !contains(github.event.pull_request.labels.*.name, 'freeze')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const checks = await github.checks.listForRef({ ...context.repo, ref: pr.head.sha });
            const allPass = checks.data.check_runs.every(c => c.conclusion === 'success');
            if (!allPass) { core.setFailed('checks not passed'); return; }
            await github.pulls.merge({ ...context.repo, pull_number: pr.number, merge_method: 'squash' });