name: exit-gate
on:
  pull_request:
  schedule:
    - cron: '17 2 * * *'  # UTC 기준

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make gate
        run: |
          make rollup
          make day49
          make day50
          make gate-objective
          make gate-exit
