name: exit-gate

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to check"
        required: false
        default: main
  push:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'tools/**'
      - 'configs/**'
      - 'slo_sla_dashboard_v1/**'
      - '.github/workflows/exit-gate.yml'
  pull_request:
    paths:
      - 'Makefile'
      - 'tools/**'
      - 'configs/**'
      - 'slo_sla_dashboard_v1/**'
      - '.github/workflows/exit-gate.yml'
  schedule:
    - cron: "17 3 * * *" # nightly

concurrency:
  group: exit-gate-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gate:
    # PR 이벤트면서 lane:ci 라벨이면 생략
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'lane:ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.sha }}
          fetch-depth: 0

      - name: Roll metrics & tune + gates
        run: |
          make rollup
          make day49
          make day50
          make gate-objective
          make gate-exit

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exit-gate-artifacts
          path: |
            slo_sla_dashboard_v1/metrics.json
            reports/objective_tuning_summary.json
            pou_retention_day21.json

      - name: Summarize
        shell: bash
        run: |
          echo "## Exit Gate Summary" >> $GITHUB_STEP_SUMMARY
          python3 - <<'PY' >> $GITHUB_STEP_SUMMARY
import json,os,sys,time,datetime as dt
def age_h(p): 
    return (time.time()-os.path.getmtime(p))/3600 if os.path.exists(p) else 1e9
m=json.load(open("slo_sla_dashboard_v1/metrics.json")) if os.path.exists("slo_sla_dashboard_v1/metrics.json") else {}
s=json.load(open("reports/objective_tuning_summary.json")) if os.path.exists("reports/objective_tuning_summary.json") else {}
n=s.get("n",0); expl=s.get("quality_score"); d21=s.get("retention_d21")
pe=s.get("p_error", m.get("p_error")); pt=s.get("p_timeout", m.get("p_timeout"))
print(f"|metric|value|")
print(f"|---|---|")
print(f"|n|{n}|"); print(f"|explain|{expl}|"); print(f"|p_error|{pe}|"); print(f"|p_timeout|{pt}|"); print(f"|d21|{d21}|")
print(f"|metrics.json age (h)|{age_h('slo_sla_dashboard_v1/metrics.json'):.2f}|")
print(f"|summary age (h)|{age_h('reports/objective_tuning_summary.json'):.2f}|")
PY