name: Regression Guard & Quality Gates
on: [push, pull_request]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r duri_core/requirements.txt
      
      - name: Run pre-commit hooks
        run: pre-commit run -a
      
      - name: CI Guard (fail-fast module loading)
        run: ./scripts/ci_guard.sh
      
      - name: Collect static metrics baseline
        run: |
          python scripts/collect_static_metrics.py
          cp metrics/current.json metrics/baseline.json || true
      
      - name: Run mutation tests
        run: |
          mutmut run --CI || true
          mutmut results > metrics/mutmut.txt || true
      
      - name: Static quality gates
        run: |
          python scripts/collect_static_metrics.py
          python scripts/gate_score.py
      
      - name: Weakpoint analysis
        run: |
          python scripts/weakpoint_topk.py || true
      
      - name: Gate Shadow Verification
        run: ./scripts/verify_gate_shadow.sh
      
      - name: Run core tests
        run: pytest -q tests/test_imports.py
      
      - name: Family mode tests
        run: pytest -q tests/test_family_mode_guard.py || true
      
      - name: SWE Runner safety test
        run: |
          python duri_evolution/agents/swe_runner.py || true
      
      - name: Upload quality metrics
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: quality-metrics
          path: |
            metrics/
            var/reports/
