name: insight-ci
on:
  push:
    paths:
      - "insight/**"
      - "tests/**"
      - "docs/insight/**"
      - "scripts/core/phase11/**"
      - "docs/phase11/**"
      - ".github/workflows/insight-ci.yml"
  pull_request:
    paths:
      - "insight/**"
      - "tests/**"
      - "docs/insight/**"
      - "scripts/core/phase11/**"
      - "docs/phase11/**"
      - ".github/workflows/insight-ci.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test deps
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-asyncio anyio
      - name: Run full test suite
        run: pytest -q
      - name: Run Phase 11 tests
        run: pytest -q tests/test_phase11_*.py
      - name: Upload Phase11 traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase11-traces
          path: DuRiCore/memory/phase11_traces/**
          if-no-files-found: ignore
