name: insight-ci
on:
  push:
    paths:
      - "insight/**"
      - "tests/**"
      - "docs/insight/**"
      - "scripts/core/phase11/**"
      - "docs/phase11/**"
      - ".github/workflows/insight-ci.yml"
  pull_request:
    paths:
      - "insight/**"
      - "tests/**"
      - "docs/insight/**"
      - "scripts/core/phase11/**"
      - "docs/phase11/**"
      - ".github/workflows/insight-ci.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install pytest numpy
      - run: pytest tests/test_insight_engine.py -q
      - run: pytest tests/test_phase11_*.py -q

  phase11-tests:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pytest tests/test_phase11_*.py -v
