name: lane-guard
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  ensure-one-lane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allowed = ["lane:experiment","lane:ops","lane:ci"];
            const labels = context.payload.pull_request.labels.map(l=>l.name);
            const lanes = labels.filter(l=>allowed.includes(l));
            core.info(`labels: ${labels.join(", ")}`);
            if (lanes.length !== 1) {
              core.setFailed(`Exactly one lane label required (${allowed.join(", ")}), got: ${lanes.join(", ")||"none"}`);
            }
