name: lint (weekly full scan)

on:
  schedule:
    - cron: "0 18 * * 6"  # 매주 일요일 03:00 KST=18:00 UTC 토요일
  workflow_dispatch:

permissions:
  contents: read

jobs:
  full-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install pre-commit
      - run: pre-commit install
      - run: pre-commit run -a --color always --show-diff-on-failure
