name: Observability CI

on:
  push:
    branches: [ main, feat/day68-observability-hybrid ]
    paths:
      - 'infra_mem_alerts_clean.rules.yml'
      - 'rules_test.yml'
      - 'grafana/duri-obsv-overview.json'
      - 'grafana/dashboards.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra_mem_alerts_clean.rules.yml'
      - 'rules_test.yml'
      - 'grafana/duri-obsv-overview.json'
      - 'grafana/dashboards.yaml'

jobs:
  observability-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install promtool
      run: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz
        tar xzf prometheus-2.48.0.linux-amd64.tar.gz
        sudo cp prometheus-2.48.0.linux-amd64/promtool /usr/local/bin/
        promtool --version

    - name: Check Prometheus rules
      run: promtool check rules infra_mem_alerts_clean.rules.yml

    - name: Test Prometheus rules
      run: promtool test rules rules_test.yml

    - name: Validate Grafana dashboard JSON
      run: jq . grafana/duri-obsv-overview.json >/dev/null

    - name: Validate Grafana provisioning YAML
      run: python3 -c "import yaml; yaml.safe_load(open('grafana/dashboards.yaml'))"

    - name: Validate Alertmanager config (skip for now)
      run: echo "Alertmanager validation skipped due to promtool version compatibility"
