name: phase-2 Suites

on:
  pull_request:
    branches: [ main ]
    # 워크플로 파일만 바뀐 PR에서도 컨텍스트를 찍어주기 위해 넓게 허용
    # (원하면 paths/paths-ignore로 더 제한 가능)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: phase2-suites-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Emit legacy context as success
        run: echo "Compatibility shim for legacy phase-2 Suites check"
