name: pre-commit autoupdate
on:
  schedule: [{cron: "0 18 * * 5"}]
  workflow_dispatch:
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install pre-commit
      - run: pre-commit autoupdate
      - run: |
          git config user.name "pre-commit-bot"
          git config user.email "pre-commit-bot@example.com"
          git checkout -b chore/pre-commit-autoupdate || git checkout chore/pre-commit-autoupdate
          git add .pre-commit-config.yaml
          git commit -m "chore: pre-commit autoupdate" || exit 0
          git push -u origin HEAD
