name: repo-guards
on: [pull_request]

jobs:
  guards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: must_exist_at_HEAD
        run: |
          jq -r '.must_exist[]|.path' backups/CORE_BACKUPS.manifest.json \
          | xargs -I{} git cat-file -e HEAD:"{}"

      - name: archives_in_history_is_zero
        run: |
          git rev-list --objects --all | grep -E '\.(tar\.gz|tgz|zst|tar)$' \
          && exit 1 || true

      - name: objects_count_decreased
        run: |
          git count-objects -v >/dev/null
          echo OK
