name: tag-policy
on:
  push:
    tags: ['v*']  # 태그에만 반응
permissions: { contents: read }

env:
  ENFORCE_SIGNED_TAGS: 'false'  # 필요 시 'true'로 변경

jobs:
  verify-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Enforce semver + annotated tag
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "Checking tag: $TAG"
          if ! echo "$TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Tag must match vMAJOR.MINOR.PATCH"
            exit 1
          fi
          # annotated 여부 확인
          if ! git for-each-ref "refs/tags/$TAG" --format='%(objecttype)' | grep -qx 'tag'; then
            echo "Tag must be annotated (not lightweight)"
            exit 1
          fi
          echo "Tag policy OK"
      - name: (옵션) GPG-signed annotated tag 확인
        if: ${{ env.ENFORCE_SIGNED_TAGS == 'true' }}
        run: |
          TAG="${GITHUB_REF##*/}"
          # 서명 검증 (해당 키가 Runner에 신뢰 키로 있어야 함)
          git tag -v "$TAG" >/dev/null 2>&1 || {
            echo "Tag is not GPG-signed or unverifiable"
            exit 1
          }
          echo "GPG signature verification OK"
