name: verify-artifacts
on: [pull_request, push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure no tracked snapshot/backup/logs
        run: |
          set -eo pipefail
          PATTERN='^(duri_snapshots|restored_day8_10|unified_conversations|logs|DuRiCore_backup_|backup|duri_archive)/'
          COUNT=$(git ls-files | grep -E "$PATTERN" | wc -l | xargs)
          if [ "$COUNT" != "0" ]; then
            echo "::error ::Still tracked artifacts found ($COUNT)."
            git ls-files | grep -E "$PATTERN" | sed 's/^/- /'
            exit 1
          fi
          echo "✅ No tracked artifacts found"
